region: us-east-1
s3_bucket_name: automation-101-cloudtrial 
role_name: CloudTrailAutomation
trail_name: aws-multi-account-cloudtrail-logs
account_ids: "661075516689,717153733799,246624127786,433806445252"
